controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_front_steer_joint
      - left_front_steer_joint
      - right_rear_steer_joint
      - left_rear_steer_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

velocity_controller:
  ros__parameters:
    joints:
      - right_front_wheel_joint
      - left_front_wheel_joint
      - right_rear_wheel_joint
      - left_rear_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity