# For parameter descriptions, please refer to the template parameter files for each node.

ekf_filter_node_odom:
  ros__parameters:
    frequency: 60.0
    two_d_mode: true
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link 
    world_frame: odom

    odom0: /jetbot_base_controller/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true,  false,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    #imu0: adnav_node/imu
    #imu0_config: [false, false, false,
    #              false,  false,  true,
    #              false, false, false,
    #              false,  false,  false,
    #              false,  false,  false]
    #imu0_differential: false  # If using a real robot you might want to set this to true, since usually absolute measurements from real imu's are not very accurate
    #imu0_relative: false
    #imu0_queue_size: 10
    #imu0_remove_gravitational_acceleration: true

    use_control: false

    transform_timeout: 0.001

    #process_noise_covariance: [0.05,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,   0.05,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,   0.06,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,   0.03,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,   0.03,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,   0.06,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  0.025,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,   0.025,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,    0.04,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,   0.01,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,   0.01,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,   0.02,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,   0.01,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,   0.01,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,  0.015]

